### ISSUE TITLE
Index Error on some meshes

### ISSUE THREAD

**Issue by FreakTheMighty** [Kramer84/pyfqmr-Fast-Quadric-Mesh-Reduction#1]
On some meshes I get this index error. I've attached a sample mesh.

```python
scene = trimesh.load('mesh.glb')
mesh = list(scene.geometry.values())[0]
mesh.merge_vertices()
simplify = pySimplify()

simplify.setMesh(mesh)
simplify.simplify_mesh(target_count = 100, aggressiveness=3, verbose=10)
new_mesh = simplify.getMesh()
new_mesh.show()
```

```

iteration 0 - triangles 620 threshold 2.7e-08
iteration 5 - triangles 572 threshold 5.12e-07
iteration 10 - triangles 570 threshold 2.197e-06
iteration 15 - triangles 570 threshold 5.832e-06
iteration 20 - triangles 570 threshold 1.2167e-05
iteration 25 - triangles 570 threshold 2.1952e-05
iteration 30 - triangles 570 threshold 3.5937e-05
iteration 35 - triangles 570 threshold 5.4872e-05
iteration 40 - triangles 570 threshold 7.9507e-05
iteration 45 - triangles 569 threshold 0.000110592
iteration 50 - triangles 569 threshold 0.000148877
iteration 55 - triangles 569 threshold 0.000195112
iteration 60 - triangles 569 threshold 0.000250047
iteration 65 - triangles 569 threshold 0.000314432
iteration 70 - triangles 569 threshold 0.000389017
iteration 75 - triangles 569 threshold 0.000474552
iteration 80 - triangles 569 threshold 0.000571787
iteration 85 - triangles 569 threshold 0.000681472
iteration 90 - triangles 569 threshold 0.000804357
iteration 95 - triangles 569 threshold 0.000941192
simplified mesh in 0.0217 seconds from 620 to 100 triangles
Traceback (most recent call last):
  File ".\simplify.py", line 12, in <module>
    new_mesh = simplify.getMesh()
  File "simplify_wrapper.pyx", line 55, in simplify_wrapper.pySimplify.getMesh
IndexError: index 569 is out of bounds for axis 0 with size 569
```
[mesh.zip](https://github.com/Kramer84/Py_Fast-Quadric-Mesh-Simplification/files/5440674/mesh.zip)

**Comment by Kramer84** [comment]
Thank you for the issue!
There was an iteration over the wrong variable, it should be fixed now.
I also added the possibility to directly pass the scene object.
