### ISSUE TITLE
Error while getting mesh

### ISSUE THREAD

**Issue by Kramer84** [Kramer84/pyfqmr-Fast-Quadric-Mesh-Reduction#7]
This codes raises an error, as some cases were not considered.
```python
import trimesh as tr
>>> import trimesh as tr
>>> import pyfqmr as fmr
>>> mesh = tr.load_mesh('Stanford_Bunny_sample.stl')
>>> simpl = fmr.Simplify()
>>> verts, faces = mesh.vertices, mesh.faces
>>> simpl.setMesh(verts, faces)
>>> simpl.getMesh()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyfqmr/Simplify.pyx", line 60, in pyfqmr.Simplify.Simplify.getMesh
  File "stringsource", line 429, in View.MemoryView.memoryview.__setitem__
  File "stringsource", line 482, in View.MemoryView.memoryview.setitem_indexed
  File "stringsource", line 398, in View.MemoryView.memoryview.get_item_pointer
  File "stringsource", line 931, in View.MemoryView.pybuffer_index
IndexError: Out of bounds on buffer access (axis 0)
```
The error comes from the fact that we have more faces than points, and that we can not mess with a memoryviews dtype, even when copying it. We have to keep an other reference to the real numpy objects, and copy the faces array using astype.

**Comment by Kramer84** [comment]
Solved here [d6ff1c7](https://github.com/Kramer84/pyfqmr-Fast-Quadric-Mesh-Reduction/commit/d6ff1c7cb39758ca1c7416a988d3f3ffe55eb81e) by creating a new Python reference object, which can store the numpy arrays without having to declare them.
